CREATE TABLE IF NOT EXISTS risk (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    risk_level VARCHAR(200) NOT NULL,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
